In [8]:
import tensorflow as tf

# Define Null Matrix
mat0 = tf.constant([ [0, 0, 0], [0, 0, 0] ])
mat1 = tf.zeros([2, 3 ] )

mat2 = tf.ones([3, 2])

mat3 = tf.fill([2, 3], 15)

matMul = tf.matmul(data1, data2)
matAdd = tf.add(data1, data3)

with tf.Session() as sess:
    print(sess.run(mat0))
    print("zeros: \n", sess.run(mat1))
    print("ones: \n", sess.run(mat2))
    print("fill: \n", sess.run(mat3))
    

[[0 0 0]
 [0 0 0]]
zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
fill: 
 [[15 15 15]
 [15 15 15]]


In [15]:
import tensorflow as tf
mat1 = tf.constant([ [2], [3] , [4] ] )
mat2 = tf.zeros_like(mat1)
mat3 = tf.lin_space(0.0, 2.0, 11)
mat4 = tf.random_uniform([2, 3], -1, 2) # Data range [-1, 2], row=2 , Col = 3
with tf.Session() as sess:
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))

[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[ 0.44977832 -0.80614746 -0.84356606]
 [ 1.864896   -0.85919046 -0.52459526]]
