In [16]:
#CURD
import numpy as np
data1 = np.array([1, 2,3,4,5])
print(data1)
data2 = np.array( [[1,2], [3, 4]])
print(data2)

print("Dimension:")
print(data1.shape, data2.shape)

print("Zeros and Ones:")
print(np.zeros([2, 3]), np.ones([2,2]))

data2[1,0] = 5
print("Update", data2)

data3 = np.ones([2, 3])
print("Multiply: ",data3*2)
print("Divide: ",data3/3)
print("Add:", data3+3)

data4 = np.array([[1, 2, 3], [4,5,6] ])
print("Matrix Add: ",data3 + data4)
print("Matrix Multiply: ", data3 * data4)

[1 2 3 4 5]
[[1 2]
 [3 4]]
Dimension:
(5,) (2, 2)
Zeros and Ones:
[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]]
Update [[1 2]
 [5 4]]
Multiply:  [[2. 2. 2.]
 [2. 2. 2.]]
Divide:  [[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
Add: [[4. 4. 4.]
 [4. 4. 4.]]
Matrix Add:  [[2. 3. 4.]
 [5. 6. 7.]]
Matrix Multiply:  [[1. 2. 3.]
 [4. 5. 6.]]
